version: '3'

tasks:
  run:
    - cat ../input.txt | ./a.exe
    - rm a.exe

  task-1:
    - gcc common.c 1/main.c
    - task: run

  task-2:
    - gcc common.c 2/main.c
    - task: run

  lines:
    - wc -l common* 1/* 2/*
