version: '3'

tasks:
  run:
    - cat ../input.txt | ./a.exe
    - rm a.exe

  task-1:
    - g++ -Wall common.cc 1/main.cc
    - task: run

  task-2:
    - g++ -Wall common.cc 2/main.cc
    - task: run

  task-2-obfuscated:
    - g++ -Wall 2/obfuscated.cc
    - task: run

  lines:
    - wc -l common* 1/* 2/*
